# Generated by Django 4.2.13 on 2026-04-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_timezone",
        ),
    ]
