# Generated by Django 4.2.13 on 2026-04-04 15:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food & Dining"),
                            ("transport", "Transport"),
                            ("housing", "Housing & Rent"),
                            ("utilities", "Utilities"),
                            ("healthcare", "Healthcare"),
                            ("entertainment", "Entertainment"),
                            ("shopping", "Shopping"),
                            ("education", "Education"),
                            ("travel", "Travel"),
                            ("salary", "Salary"),
                            ("freelance", "Freelance"),
                            ("investment", "Investment Returns"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("expense", "Expense"), ("income", "Income")],
                        default="expense",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("receipt_url", models.URLField(blank=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expenses",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="expenses_user_id_513cb5_idx"
                    ),
                    models.Index(
                        fields=["user", "type"], name="expenses_user_id_5ae6c2_idx"
                    ),
                    models.Index(
                        fields=["user", "category"], name="expenses_user_id_ed2a40_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food & Dining"),
                            ("transport", "Transport"),
                            ("housing", "Housing & Rent"),
                            ("utilities", "Utilities"),
                            ("healthcare", "Healthcare"),
                            ("entertainment", "Entertainment"),
                            ("shopping", "Shopping"),
                            ("education", "Education"),
                            ("travel", "Travel"),
                            ("salary", "Salary"),
                            ("freelance", "Freelance"),
                            ("investment", "Investment Returns"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "budgets",
                "unique_together": {("user", "category")},
            },
        ),
    ]
